name: Validate Home Assistant config

on:
  pull_request:
  push:

jobs:
  ha-config-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Home Assistant configuration
        uses: frenck/action-home-assistant@v1
        with:
          path: ./
